In [1]:
import numpy as np
import pandas as pd

In [2]:
Titanic = pd.read_csv('titanic.csv')
Titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
Titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [14]:
Titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [16]:
Titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [13]:
Titanic.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [3]:
Titanic[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [4]:
Titanic['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [5]:
Titanic['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

### How Many Men And Female were on the Ship?

In [6]:
Titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### What Part of passangers managed to Survive ?

In [7]:
Survival_Precentage= format((Titanic['Survived'].value_counts().values[1]/Titanic['Survived'].value_counts().sum())*100)
Survival_Precentage = round(float(Survival_Precentage),2)
print(f" The Survival Precentage is : {Survival_Precentage} %")

 The Survival Precentage is : 38.38 %

### What is the Proportion of First-Class Passangers?

In [8]:
Titanic['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [9]:
FirstClass_Precentage= format((Titanic['Pclass'].value_counts().values[1]/Titanic['Pclass'].value_counts().sum())*100)
FirstClass_Precentage = round(float(FirstClass_Precentage),2)
print(f" The First Class Passangers Precentage is : {FirstClass_Precentage} %")

 The First Class Passangers Precentage is : 24.24 %

### How old Were the Passangers?

In [10]:
Mean_Age = Titanic['Age'].mean()
Median_Age = Titanic['Age'].median()
print(f"The Mean Age is : {Mean_Age}"+" "+f"The Median Age is : {Median_Age} ")

The Mean Age is : 29.69911764705882 The Median Age is : 28.0

### Does the Number of correlate with the Number of parents/Children ?

In [11]:
print(Titanic[['SibSp', 'Survived']].groupby(['SibSp']).mean())
print('\n\n')
print(Titanic[['Parch', 'Survived']].groupby(['Parch']).mean())

       Survived
SibSp
0      0.345395
1      0.535885
2      0.464286
3      0.250000
4      0.166667
5      0.000000
8      0.000000



       Survived
Parch
0      0.343658
1      0.550847
2      0.500000
3      0.600000
4      0.000000
5      0.200000
6      0.000000

In [17]:
correlation = Titanic['SibSp'].corr(Titanic['Parch'])
print("Pearson correlation:", round(correlation,2))

Pearson correlation: 0.41

In [19]:
correlation_Class = Titanic['Pclass'].corr(Titanic['Survived'])
print("Pearson correlation between Pclass and Survived:", round(correlation_Class,2))

Pearson correlation between Pclass and Survived: -0.34

What is the most popular female name on the ship? Extract the passenger’s full name
(Name column) from his name (First Name). This task is a typical example of what a data
analysis specialist is faced with. The data is very heterogeneous and noisy, but you need to
extract the necessary information from it. Try to manually parse several values of the Name
column and work out a rule for extracting names, as well as dividing them into female and
male.

In [21]:
def extract_gender_and_first_name(name):
    # Split last name, rest
    parts = name.split(', ')
    if len(parts) > 1:
        rest = parts[1]  # "Title. First Name(s)"
        title, *first_names = rest.split(' ')
        if title in ['Miss.', 'Mrs.']:
            gender = 'female'
        else:
            gender = 'male'
        # join first names as string
        first_name = ' '.join(first_names)
        return gender, first_name
    else:
        return None, None

In [31]:
Titanic['Gender_Name'] = Titanic['Name'].apply(lambda x: extract_gender_and_first_name(x))
Titanic['Gender'] = Titanic['Gender_Name'].apply(lambda x: x[0])
Titanic['First_Name'] = Titanic['Gender_Name'].apply(lambda x: x[1])

In [32]:
print(Titanic['Gender_Name'])

0                                  (male, Owen Harris)
1      (female, John Bradley (Florence Briggs Thayer))
2                                      (female, Laina)
3              (female, Jacques Heath (Lily May Peel))
4                                (male, William Henry)
                            ...
886                                     (male, Juozas)
887                           (female, Margaret Edith)
888                 (female, Catherine Helen "Carrie")
889                                (male, Karl Howell)
890                                    (male, Patrick)
Name: Gender_Name, Length: 891, dtype: object

In [33]:
print(Titanic['Gender'].value_counts())

Gender
male      584
female    307
Name: count, dtype: int64

In [34]:
print(Titanic['First_Name'].max())

Yousseff

In [41]:
# Most popular female name
popular_female = Titanic[Titanic['Gender']=='female']['First_Name'].value_counts()
print(popular_female)

First_Name
Mary                                  6
Bertha                                4
Anna Sofia                            3
Anna                                  3
Hanora "Nora"                         2
                                     ..
Augusta Charlotta                     1
Kornelia Theodosia                    1
(Elizabeth Anne Maidment)             1
Amelia                                1
James (Helene DeLaudeniere Chaput)    1
Name: count, Length: 288, dtype: int64