In [2]:
import numpy as np
import pandas as pd

In [3]:
Titanic = pd.read_csv('titanic.csv')
Titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
Titanic[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [6]:
Titanic['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [7]:
Titanic['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

### How Many Men And Female were on the Ship?

In [8]:
Titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### What Part of passangers managed to Survive ?

In [39]:
Survival_Precentage= format((Titanic['Survived'].value_counts().values[1]/Titanic['Survived'].value_counts().sum())*100)
Survival_Precentage = round(float(Survival_Precentage),2)
print(f" The Survival Precentage is : {Survival_Precentage} %")

 The Survival Precentage is : 38.38 %

### What is the Proportion of First-Class Passangers?

In [41]:
Titanic['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [44]:
FirstClass_Precentage= format((Titanic['Pclass'].value_counts().values[1]/Titanic['Pclass'].value_counts().sum())*100)
FirstClass_Precentage = round(float(FirstClass_Precentage),2)
print(f" The First Class Passangers Precentage is : {FirstClass_Precentage} %")

 The First Class Passangers Precentage is : 24.24 %

### How old Were the Passangers?

In [50]:
Mean_Age = Titanic['Age'].mean()
Median_Age = Titanic['Age'].median()
print(f"The Mean Age is : {Mean_Age}"+" "+f"The Median Age is : {Median_Age} ")

The Mean Age is : 29.36158249158249 The Median Age is : 28.0

### Does the Number of correlate with the Number of parents/Children ?

In [52]:
print(Titanic[['SibSp', 'Survived']].groupby(['SibSp']).mean())
print('\n\n')
print(Titanic[['Parch', 'Survived']].groupby(['Parch']).mean())

       Survived
SibSp
0      0.345395
1      0.535885
2      0.464286
3      0.250000
4      0.166667
5      0.000000
8      0.000000



       Survived
Parch
0      0.343658
1      0.550847
2      0.500000
3      0.600000
4      0.000000
5      0.200000
6      0.000000